apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: fleetman
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:3.6.5-jessie
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          # pointer to the configuration of HOW we want the mount to be implemented
          persistentVolumeClaim:
            claimName: mongo-pvc
---
# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: fleetman
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# How do we want it implemented
apiVersion: storage.k8s.io/v1
kind: PersistentVolume
metadata:
  name: cloud-ssd
  namespace: fleetman
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
---
kind: Service
apiVersion: v1
metadata:
  name: fleetman-mongodb
  namespace: fleetman
spec:
  selector:
    app: mongodb
  ports:
    - name: mongoport
      port: 27017
  type: ClusterIP
